### ISSUE TITLE
Can't run task because of reportedly empty mail address

### ISSUE THREAD

**Issue by Aero91** [format-gmbh/format_t3tools#1]
Hi there,

if I try to run a task it throws the following error:
`
Execution of task “Log files size check (format_t3tools)” failed with the following message: Email “” does not comply with addr-spec of RFC 2822.`

But Email shouldn't be empty since I declared it.

T3 Version: 10.4.12 Composer Mode
Extension Version: 2.2.2

**Comment by format-gmbh** [comment]
Have you thought about the global setting for defaultMailFromAddress?

**Comment by Aero91** [comment]
No I haven't... thanks.
Is it possbile to configure the path to check for logfiles?
My logfiles are located in /var/log/ and not in public/typo3temp/var/log/

**Comment by format-gmbh** [comment]
Yes, that would be possible.

**Comment by format-gmbh** [comment]
I have released a new version 2.2.3 and hope my bugfix solves your problem.
